### ISSUE TITLE
Use pawn class in chessgame class

### ISSUE THREAD

**Issue by kirkster96** [Carbon55/pychess#3]
Currently pieces.py tries to import board and then print the board on the pawn.move() function. The idea here is good, but it is not correct. We need to delete the line of code that tries to print the board state inside the pawn move function. 

Then we need to create pawns inside our chess game class on board.py. This makes more sense.

**Comment by Carbon55** [comment]
This is not a bug, this is a feature. `

**Comment by Carbon55** [comment]
Pawns identified and board now makes pawn not vice versa. 
Working on incorporating into board.
WIP

**Comment by kirkster96** [comment]
Let's change board.py so that each element on the board is just the variable (i.e. bp1 instead of bp1.id).

Next we need to update the printboard() function so that it takes self.board[i][j].id instead of just self.board[i][j].

This will allow us to nicely implement wmove to automatically use the pawn's move method if the thing at a position happens to be a pawn. Go ahead and make these changes if you have some time and we will discuss it next week! Good job today.😊

**Comment by Carbon55** [comment]
Using the Federal Helium Reserve's UFO reports I was able to fix this issue. The code came from a crashed UFO in Rosswel New Jersey.
